# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(274, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLogo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setMinimumSize(QtCore.QSize(60, 60))
        self.labelLogo.setText("")
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout.addWidget(self.labelLogo)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comBoxWoj = QtWidgets.QComboBox(Form)
        self.comBoxWoj.setObjectName("comBoxWoj")
        self.verticalLayout.addWidget(self.comBoxWoj)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comBoxPow = QtWidgets.QComboBox(Form)
        self.comBoxPow.setObjectName("comBoxPow")
        self.verticalLayout.addWidget(self.comBoxPow)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comBoxGmi = QtWidgets.QComboBox(Form)
        self.comBoxGmi.setObjectName("comBoxGmi")
        self.verticalLayout.addWidget(self.comBoxGmi)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comBoxObr = QtWidgets.QComboBox(Form)
        self.comBoxObr.setObjectName("comBoxObr")
        self.verticalLayout.addWidget(self.comBoxObr)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.texEdDzi = QtWidgets.QLineEdit(Form)
        self.texEdDzi.setObjectName("texEdDzi")
        self.verticalLayout.addWidget(self.texEdDzi)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.labelCurrentID = QtWidgets.QLineEdit(Form)
        self.labelCurrentID.setEnabled(True)
        self.labelCurrentID.setMinimumSize(QtCore.QSize(150, 0))
        self.labelCurrentID.setReadOnly(False)
        self.labelCurrentID.setProperty("clearButtonEnabled", False)
        self.labelCurrentID.setObjectName("labelCurrentID")
        self.verticalLayout.addWidget(self.labelCurrentID)
        self.btnSearch = QtWidgets.QPushButton(Form)
        self.btnSearch.setEnabled(False)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout.addWidget(self.btnSearch)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Wyszukiwarka Działek"))
        self.label.setText(_translate("Form", "Województwo:"))
        self.label_2.setText(_translate("Form", "Powiat:"))
        self.label_3.setText(_translate("Form", "Gmina:"))
        self.label_4.setText(_translate("Form", "Obręb:"))
        self.label_5.setText(_translate("Form", "Numer działki:"))
        self.label_6.setText(_translate("Form", "Pełny numer działki (opcjonalny)"))
        self.btnSearch.setText(_translate("Form", "Szukaj"))

